title: Eupheng Vue
baseURL: /
params:
  description: Eupheng Vue
  layout: boxed
  style: minimal
  palette: gray
  mode: light
  base_font: serif
  header:
    type: header
    title: Logo
    logo: /images/2CCB028A-2EE2-496A-B685-754D0ABF15F9.png
    has_primary_nav: false
    primary_nav_links: []
    has_secondary_nav: true
    secondary_nav_links:
      - label: About
        url: ''
        style: link
        has_icon: false
        icon: arrow-left
        icon_position: right
        new_window: false
        type: action
      - label: Blog
        url: /blog
        style: link
        has_icon: false
        icon: arrow-left
        icon_position: right
        new_window: false
        type: action
      - type: action
        label: Contact
        url: /contact
        style: primary
    has_anncmnt: false
    anncmnt_content: >-
      Curabitur ac tellus mattis, tempor ipsum eu, eleifend sapien. **[Learn
      More](/pricing/)**
    anncmnt_align: right
    anncmnt_is_home_only: true
    anncmnt_has_close: true
    anncmnt_id: new-features
  footer:
    type: footer
    has_primary_nav: false
    primary_nav_title: Company
    primary_nav_links:
      - type: action
        label: About
        url: /about
        style: link
      - type: action
        label: Style Guide
        url: /style-guide
        style: link
    has_secondary_nav: false
    secondary_nav_title: Blog
    secondary_nav_links:
      - type: action
        label: News
        url: /blog/category/news
        style: link
    has_tertiary_nav: false
    tertiary_nav_title: Legal
    tertiary_nav_links:
      - type: action
        label: Terms & Conditions
        url: /terms-conditions
        style: link
      - type: action
        label: Privacy Policy
        url: /privacy-policy
        style: link
    has_social: true
    social_links:
      - type: action
        label: Twitter
        url: 'https://twitter.com/euvuedotme'
        style: link
        has_icon: true
        icon: twitter
        icon_position: center
        new_window: true
      - type: action
        label: GitHub
        url: 'https://github.com/euvue'
        style: link
        has_icon: true
        icon: github
        icon_position: center
        new_window: true
      - type: action
        label: LinkedIn
        url: 'https://www.linkedin.com/in/euvue/'
        style: link
        has_icon: true
        icon: linkedin
        icon_position: center
        new_window: true
    content: '&copy; Eupheng Vue All rights reserved.'
    links:
      - type: action
        label: Made with Stackbit.
        url: 'https://www.stackbit.com'
        style: link
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
